// Writes each app's build-info.ts with the current git sha + build time, so the
// running bundle can show which build it is. Embedded at build time rather than
// fetched at runtime on purpose: a stale cached page then shows its OWN old
// stamp, which is the whole point — it lets you spot a stale cache instead of
// being reassured by the server's current version. The generated files are
// gitignored.
//
// The console needed this most and had it least. Its page lives in a WebView on
// a phone that Android freezes and caches, so "is what I am looking at current?"
// is a question asked often — and until now neither of us could answer it. The
// pattern is recall's, unchanged; see frontend/scripts/stamp-version.mjs there.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/** Both apps in this workspace: memview itself, and the agent console. */
const APPS = [
  join(here, '..', 'src', 'app', 'build-info.ts'),
  join(here, '..', 'projects', 'console-web', 'src', 'app', 'build-info.ts'),
];

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

const sha = git('rev-parse --short HEAD') || 'nogit';
// A gitignored build-info.ts won't dirty the tree; any real uncommitted change marks the build.
const dirty = git('status --porcelain') ? '+' : '';
const builtAt = new Date().toISOString();

for (const out of APPS) {
  writeFileSync(
    out,
    `// Generated by scripts/stamp-version.mjs at build time. Do not edit — gitignored.
export const BUILD_INFO = {
  sha: '${sha}${dirty}',
  builtAt: '${builtAt}',
} as const;
`,
  );
}
console.log(`stamped build-info: ${sha}${dirty} @ ${builtAt}`);
