// Measure the graph layout without a browser.
//
//   node scripts/graph-report.mjs                 synthetic corpus-scale graph
//   node scripts/graph-report.mjs graph.json      a saved /api/graph response
//
// Every bug this view has had was invisible until someone measured, and the
// measuring was done once, by hand, outside the app: zoom was a silent no-op
// that left a 330-unit graph clipped in a 412px canvas; a degree cutoff drew
// ~25 colliding labels; link forces alone smeared the sections into one ball.
// None of them threw, none failed a lint, and the picture looked plausible.
//
// So the numbers that would have caught them are printed here instead of
// re-derived. The layout module is pure and TestBed-free precisely so this can
// run under plain Node — this is what that design was for.
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const here = new URL('..', import.meta.url).pathname;

// Bundle the TypeScript through the esbuild that Angular already depends on,
// rather than adding a loader or duplicating the maths in JavaScript.
const out = join(mkdtempSync(join(tmpdir(), 'graph-report-')), 'layout.mjs');
const build = spawnSync(
  join(here, 'frontend/node_modules/.bin/esbuild'),
  [
    join(here, 'frontend/src/app/graph-layout.ts'),
    '--bundle',
    '--format=esm',
    `--outfile=${out}`,
  ],
  { encoding: 'utf8' },
);
if (build.status !== 0) {
  console.error(build.stderr || 'esbuild failed');
  process.exit(1);
}

const layout = await import(out);

/**
 * A graph the size and shape of the live corpus.
 *
 * Synthetic so this runs in CI, where the real corpus is deliberately absent —
 * but shaped like it: roughly 350 memories across a dozen sections, and about
 * half the links crossing a section boundary, which is the property that made
 * colour alone insufficient to keep the sections apart.
 */
function syntheticGraph(nodeCount = 350, sectionCount = 12) {
  const nodes = Array.from({ length: nodeCount }, (_, i) => ({
    name: `memory_number_${i}`,
    section: `Section ${i % sectionCount}`,
    in_degree: 0,
    out_degree: 0,
  }));
  const edges = [];
  const link = (a, b) => {
    if (a === b) return;
    edges.push({ source: nodes[a].name, target: nodes[b].name });
    nodes[a].out_degree++;
    nodes[b].in_degree++;
  };
  // Roughly half the links inside a section, half crossing — which is what the
  // real corpus does, and the whole reason colour alone was not enough to keep
  // the sections apart.
  //
  // Getting this wrong makes the report lie in the most convincing way: edges
  // generated by fixed strides cross a section almost every time, so nothing but
  // the anchors holds a section together, the ratio sits at 1.0, and the
  // threshold reports a layout regression that is really a defect in the test
  // data. Deterministic strides are still right for reproducibility — they just
  // have to be applied within a section as well as across.
  for (let i = 0; i < nodeCount; i++) {
    const section = i % sectionCount;
    // Two neighbours inside the same section.
    for (const step of [1, 2]) {
      const j = (i + step * sectionCount) % nodeCount;
      if (j % sectionCount === section) link(i, j);
    }
    // Two that cross it.
    for (const stride of [7, 53]) {
      link(i, (i * stride + 11) % nodeCount);
    }
  }
  return { nodes, edges };
}

const file = process.argv[2];
const graph = file
  ? JSON.parse(readFileSync(file, 'utf8'))
  : syntheticGraph();

const inputs = graph.nodes.map((n) => ({ name: n.name, section: n.section ?? null }));
const sections = [...new Set(inputs.map((n) => n.section))].filter((s) => s !== null);
const state = layout.createLayout(inputs, graph.edges, sections);

// A phone, because that is the narrowest thing this has to work on and the
// clipping bug only showed at that width.
const WIDTH = 412;
const HEIGHT = 732;

// How far the graph spreads while it settles, expressed as the zoom the camera
// would need at each end. The view used to fit only once the layout stopped
// moving, so it sat at zoom 1 for the whole simulation and then snapped — this
// is the size of that snap, and the reason the fit now runs every frame.
const seededRadius = layout.boundingRadius(state);
const seededZoom = layout.fitZoom(seededRadius, WIDTH, HEIGHT);

// The simulation cools through `alpha`; SETTLED is the threshold the view uses
// to stop stepping. The cap is a backstop, not the expected exit.
let steps = 0;
const MAX_STEPS = 2000;
while (steps < MAX_STEPS && state.alpha > layout.SETTLED) {
  layout.stepLayout(state);
  steps++;
}

const radius = layout.boundingRadius(state);
const zoom = layout.fitZoom(radius, WIDTH, HEIGHT);

// yaw and pitch are required: omitting them yields NaN coordinates and a report
// that confidently claims every node is off-canvas. Angled rather than
// axis-aligned, because that is how the view actually presents the graph.
const camera = { yaw: 0.6, pitch: 0.35, distance: 900, zoom };
const projected = state.nodes.map((n, i) => ({
  name: n.name,
  section: inputs[i].section,
  degree: (graph.nodes[i].in_degree ?? 0) + (graph.nodes[i].out_degree ?? 0),
  pos: n.pos,
  p: layout.project(n.pos, camera, WIDTH, HEIGHT),
}));

const onCanvas = projected.filter(
  (e) => e.p.x >= 0 && e.p.x <= WIDTH && e.p.y >= 0 && e.p.y <= HEIGHT,
).length;

// Approximate text measurement. The real canvas measures the actual font; this
// is close enough to compare label pressure between runs, and is stated as an
// approximation rather than passed off as the real width.
const measure = (text) => text.length * 6.5;
const plan = layout.planLabels(
  projected.map((e) => ({
    name: e.name,
    x: e.p.x,
    y: e.p.y,
    radius: 4,
    degree: e.degree,
    pinned: false,
  })),
  measure,
  WIDTH,
);

/** Mean distance between nodes in the same section, and across sections. */
function sectionSeparation() {
  let intra = 0;
  let intraCount = 0;
  let inter = 0;
  let interCount = 0;
  // Section comes from the input list, not the layout node — a LayoutNode
  // carries an `anchor`, not a section, and reading a field that is not there
  // silently makes every pair "same section" and the ratio NaN.
  const list = projected;
  for (let i = 0; i < list.length; i++) {
    for (let j = i + 1; j < list.length; j++) {
      const a = list[i];
      const b = list[j];
      const d = Math.hypot(a.pos.x - b.pos.x, a.pos.y - b.pos.y, a.pos.z - b.pos.z);
      if (a.section === b.section) {
        intra += d;
        intraCount++;
      } else {
        inter += d;
        interCount++;
      }
    }
  }
  return intraCount && interCount ? intra / intraCount / (inter / interCount) : NaN;
}

const ratio = sectionSeparation();

const report = {
  source: file ?? 'synthetic',
  nodes: graph.nodes.length,
  edges: graph.edges.length,
  sections: sections.length,
  settleSteps: steps,
  seededRadius: Number(seededRadius.toFixed(1)),
  boundingRadius: Number(radius.toFixed(1)),
  canvas: `${WIDTH}x${HEIGHT}`,
  seededZoom: Number(seededZoom.toFixed(4)),
  fitZoom: Number(zoom.toFixed(4)),
  zoomTravel: `${(seededZoom / zoom).toFixed(2)}x over ${steps} steps`,
  nodesOnCanvas: `${onCanvas}/${graph.nodes.length}`,
  labelsDrawn: plan.drawn.length,
  labelsCollided: plan.collided,
  labelsOffCanvas: plan.offCanvas,
  labelsOverBudget: plan.overBudget,
  labelBudget: layout.LABEL_BUDGET,
  intraOverInter: Number(ratio.toFixed(3)),
};

for (const [k, v] of Object.entries(report)) {
  console.log(`${k.padEnd(18)} ${v}`);
}

// The three historical bugs, as thresholds. Failing here is the whole point:
// these were all "the picture looks a bit wrong", which is not something CI can
// notice, and each one shipped.
const problems = [];
if (report.fitZoom === 1) {
  problems.push('fitZoom is exactly 1 — the fit is a no-op again (scale must not derive from distance alone)');
}
if (onCanvas < graph.nodes.length * 0.9) {
  problems.push(`only ${report.nodesOnCanvas} nodes land on the canvas — the graph is clipped`);
}
if (plan.drawn.length > layout.LABEL_BUDGET) {
  problems.push(`${plan.drawn.length} labels drawn, over the budget of ${layout.LABEL_BUDGET}`);
}
if (Number.isFinite(ratio) && ratio > 0.85) {
  problems.push(`sections are not holding together (intra/inter ${report.intraOverInter}, want well under 1)`);
}

if (problems.length) {
  console.error('\nFAIL');
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
console.log('\nOK');
