// Measure the graph layout without a browser.
//
//   node scripts/graph-report.mjs                 synthetic corpus-scale graph
//   node scripts/graph-report.mjs graph.json      a saved /api/graph response
//
// Every bug this view has had was invisible until someone measured, and the
// measuring was done once, by hand, outside the app: zoom was a silent no-op
// that left a 330-unit graph clipped in a 412px canvas; a degree cutoff drew
// ~25 colliding labels; link forces alone smeared the sections into one ball.
// None of them threw, none failed a lint, and the picture looked plausible.
//
// So the numbers that would have caught them are printed here instead of
// re-derived. The layout module is pure and TestBed-free precisely so this can
// run under plain Node — this is what that design was for.
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const here = new URL('..', import.meta.url).pathname;

// Bundle the TypeScript through esbuild rather than adding a loader or
// duplicating the maths in JavaScript.
//
// esbuild is a declared devDependency of the frontend because of this line. It
// used to be borrowed from Angular's transitive tree, which npm hoists flat and
// pnpm does not: under a strict node_modules the binary simply was not there,
// and an undeclared dependency that happens to be reachable is a build that
// works by accident.
const out = join(mkdtempSync(join(tmpdir(), 'graph-report-')), 'layout.mjs');
const build = spawnSync(
  join(here, 'frontend/node_modules/.bin/esbuild'),
  [
    join(here, 'frontend/src/app/graph-layout.ts'),
    '--bundle',
    '--format=esm',
    `--outfile=${out}`,
  ],
  { encoding: 'utf8' },
);
// build.error is the spawn itself failing — a missing binary lands here with
// stderr null, so reporting only stderr prints a bare "esbuild failed" and
// throws away the one fact that identifies it. That is exactly what it did.
if (build.error || build.status !== 0) {
  console.error(build.error?.message ?? build.stderr ?? `esbuild exited ${build.status}`);
  process.exit(1);
}

const layout = await import(out);

/**
 * A graph the size and shape of the live corpus.
 *
 * Synthetic so this runs in CI, where the real corpus is deliberately absent —
 * but shaped like it: roughly 350 memories across a dozen sections, and about
 * half the links crossing a section boundary, which is the property that made
 * colour alone insufficient to keep the sections apart.
 */
function syntheticGraph(nodeCount = 350, sectionCount = 12) {
  const nodes = Array.from({ length: nodeCount }, (_, i) => ({
    name: `memory_number_${i}`,
    section: `Section ${i % sectionCount}`,
    in_degree: 0,
    out_degree: 0,
  }));
  const edges = [];
  const link = (a, b) => {
    if (a === b) return;
    edges.push({ source: nodes[a].name, target: nodes[b].name });
    nodes[a].out_degree++;
    nodes[b].in_degree++;
  };
  // Roughly half the links inside a section, half crossing — which is what the
  // real corpus does, and the whole reason colour alone was not enough to keep
  // the sections apart.
  //
  // Getting this wrong makes the report lie in the most convincing way: edges
  // generated by fixed strides cross a section almost every time, so nothing but
  // the anchors holds a section together, the ratio sits at 1.0, and the
  // threshold reports a layout regression that is really a defect in the test
  // data. Deterministic strides are still right for reproducibility — they just
  // have to be applied within a section as well as across.
  for (let i = 0; i < nodeCount; i++) {
    const section = i % sectionCount;
    // Two neighbours inside the same section.
    for (const step of [1, 2]) {
      const j = (i + step * sectionCount) % nodeCount;
      if (j % sectionCount === section) link(i, j);
    }
    // Two that cross it.
    for (const stride of [7, 53]) {
      link(i, (i * stride + 11) % nodeCount);
    }
  }
  return { nodes, edges };
}

const file = process.argv[2];
const graph = file
  ? JSON.parse(readFileSync(file, 'utf8'))
  : syntheticGraph();

const names = graph.nodes.map((n) => n.name);
const curated = new Map(graph.nodes.map((n) => [n.name, n.section ?? null]));

// The clusters the LINKS form, which is what the picture is anchored on — not
// the curated MEMORY.md sections, which are compared against them below.
const levels = layout.clusterLevels(names, graph.edges);
const READABLE = 20;
let rung = 0;
levels.forEach((level, i) => {
  if (Math.abs(level.length - READABLE) < Math.abs(levels[rung].length - READABLE)) rung = i;
});
const chosen = [...(levels[rung] ?? [])].sort((a, b) => b.members.length - a.members.length);
const clusterOf = new Map();
chosen.forEach((c, i) => c.members.forEach((m) => clusterOf.set(m, i)));

// Affinities move the picture but must not tear it apart; both effects are
// measured below. Absent from the synthetic graph, which is the point — the
// layout has to be sane without them.
const affinities = graph.affinities ?? [];

const inputs = names.map((name) => {
  const c = chosen[clusterOf.get(name)];
  // A cluster of one is handed no group, so it anchors at the origin instead of
  // claiming territory of its own.
  return { name, group: c && c.members.length > 1 ? c.core : null };
});
const sections = chosen.filter((c) => c.members.length > 1).map((c) => c.core);
const state = layout.createLayout(inputs, graph.edges, sections, affinities);

// A phone, because that is the narrowest thing this has to work on and the
// clipping bug only showed at that width.
const WIDTH = 412;
const HEIGHT = 732;

// How far the graph spreads while it settles, expressed as the zoom the camera
// would need at each end. The view used to fit only once the layout stopped
// moving, so it sat at zoom 1 for the whole simulation and then snapped — this
// is the size of that snap, and the reason the fit now runs every frame.
const seededRadius = layout.boundingRadius(state);
const seededZoom = layout.fitZoom(seededRadius, WIDTH, HEIGHT);

// The simulation cools through `alpha`; SETTLED is the threshold the view uses
// to stop stepping. The cap is a backstop, not the expected exit.
let steps = 0;
const MAX_STEPS = 2000;
while (steps < MAX_STEPS && state.alpha > layout.SETTLED) {
  layout.stepLayout(state);
  steps++;
}

const radius = layout.boundingRadius(state);
const zoom = layout.fitZoom(radius, WIDTH, HEIGHT);

// yaw and pitch are required: omitting them yields NaN coordinates and a report
// that confidently claims every node is off-canvas. Angled rather than
// axis-aligned, because that is how the view actually presents the graph.
const camera = { yaw: 0.6, pitch: 0.35, distance: 900, zoom, target: { x: 0, y: 0, z: 0 } };
const projected = state.nodes.map((n, i) => ({
  name: n.name,
  section: inputs[i].group,
  degree: (graph.nodes[i].in_degree ?? 0) + (graph.nodes[i].out_degree ?? 0),
  pos: n.pos,
  p: layout.project(n.pos, camera, WIDTH, HEIGHT),
}));

const onCanvas = projected.filter(
  (e) => e.p.x >= 0 && e.p.x <= WIDTH && e.p.y >= 0 && e.p.y <= HEIGHT,
).length;

// Approximate text measurement. The real canvas measures the actual font; this
// is close enough to compare label pressure between runs, and is stated as an
// approximation rather than passed off as the real width.
const measure = (text) => text.length * 6.5;
const plan = layout.planLabels(
  projected.map((e) => ({
    name: e.name,
    x: e.p.x,
    y: e.p.y,
    radius: 4,
    degree: e.degree,
    pinned: false,
  })),
  measure,
  WIDTH,
);

/** Mean distance between nodes in the same section, and across sections. */
function sectionSeparation() {
  let intra = 0;
  let intraCount = 0;
  let inter = 0;
  let interCount = 0;
  // The group comes from the input list, not the layout node — a LayoutNode
  // carries an `anchor`, not a group, and reading a field that is not there
  // silently makes every pair "same group" and the ratio NaN.
  const list = projected;
  for (let i = 0; i < list.length; i++) {
    for (let j = i + 1; j < list.length; j++) {
      const a = list[i];
      const b = list[j];
      const d = Math.hypot(a.pos.x - b.pos.x, a.pos.y - b.pos.y, a.pos.z - b.pos.z);
      if (a.section === b.section) {
        intra += d;
        intraCount++;
      } else {
        inter += d;
        interCount++;
      }
    }
  }
  return intraCount && interCount ? intra / intraCount / (inter / interCount) : NaN;
}

const ratio = sectionSeparation();

/**
 * Whether the graph can actually be *walked*, as opposed to looked at.
 *
 * A walk is: stand on a memory, read a list of where you can go, step, repeat.
 * That fails in two ways the picture cannot show. If the typical memory has
 * dozens of neighbours the hop list is a wall of text and choosing is no easier
 * than it was on the canvas. And if focusing does not tighten the camera, the
 * step is purely textual — the reader is told they moved while the picture
 * stays a distant ball.
 */
function walkability() {
  const counts = inputs.map((n) => layout.neighboursOf(graph.edges, n.name).length);
  const sorted = [...counts].sort((a, b) => a - b);
  const median = sorted[Math.floor(sorted.length / 2)] ?? 0;

  // Focus the busiest memory — the worst case for both fitting a neighbourhood
  // on the canvas and for the length of the hop list.
  const busiest = inputs[counts.indexOf(Math.max(...counts))]?.name ?? inputs[0].name;
  const lit = layout.neighbourhood(graph.edges, inputs.map((n) => n.name), busiest, 1);
  const framing = layout.frameFor(state, busiest, lit, WIDTH, HEIGHT);
  const focusCam = { ...camera, zoom: framing.zoom, target: framing.target };

  // With `isolate` on, only the lit set is drawn — so only the lit set has to
  // land on the canvas, and all of it must.
  let onScreen = 0;
  for (const entry of projected) {
    if (!lit.has(entry.name)) continue;
    const p = layout.project(entry.pos, focusCam, WIDTH, HEIGHT);
    if (p.x >= 0 && p.x <= WIDTH && p.y >= 0 && p.y <= HEIGHT) onScreen++;
  }
  return {
    busiest,
    median,
    max: sorted.at(-1) ?? 0,
    litHere: lit.size,
    onScreen,
    zoomGain: framing.zoom / zoom,
  };
}

const walk = walkability();

/**
 * How much closer the affinities actually pull, measured against the same graph
 * laid out without them.
 *
 * The obvious metric — co-used distance against the mean distance between all
 * pairs — is worthless, and provably so: setting the spring to zero moved it
 * from 0.55 to 0.58. Co-used memories are largely the same memories the corpus
 * already links, so they sit close whether or not this force exists, and the
 * ratio measures that correlation rather than anything the layout did.
 *
 * Two settled runs is the only honest comparison. It doubles the report's work,
 * which is a fair price for a number that can distinguish a working force from
 * an inert one.
 */
function affinityPull() {
  if (affinities.length === 0) return null;
  const bare = layout.createLayout(inputs, graph.edges, sections, []);
  for (let i = 0; i < steps; i++) layout.stepLayout(bare);

  const mean = (state) => {
    const at = new Map(state.nodes.map((n) => [n.name, n.pos]));
    let total = 0;
    let count = 0;
    for (const f of affinities) {
      const p = at.get(f.a);
      const q = at.get(f.b);
      if (!p || !q) continue;
      total += Math.hypot(p.x - q.x, p.y - q.y, p.z - q.z);
      count++;
    }
    return count ? total / count : null;
  };
  const withPull = mean(state);
  const without = mean(bare);
  if (withPull === null || without === null || without === 0) return null;
  return { pairs: affinities.length, ratio: withPull / without };
}

const pull = affinityPull();

/**
 * Whether the dashed co-use layer is worth drawing, on the two grounds it could
 * fail on.
 *
 * It is redundant if the companions are the same memories the links already
 * reach — then every dash lies on top of an edge and says nothing. And it is
 * illegible if, with the camera framed on the link neighbourhood, the
 * companions land off the canvas — then the reader gets a dash running to
 * nowhere. Neither is visible in a screenshot of a picture that looks fine.
 *
 * Measured across every memory that has companions at all, not on one focus:
 * the busiest memory is the least representative, since it is the one whose
 * links already reach everywhere.
 */
function coUseReach() {
  if (affinities.length === 0) return null;
  let total = 0;
  let beyondLinks = 0;
  let onCanvasCount = 0;
  let withCompanions = 0;
  for (const input of inputs) {
    const mates = layout.companionsOf(affinities, graph.edges, input.name);
    if (mates.length === 0) continue;
    withCompanions++;
    const lit = layout.neighbourhood(graph.edges, names, input.name, 1);
    const framing = layout.frameFor(state, input.name, lit, WIDTH, HEIGHT);
    const cam = { ...camera, zoom: framing.zoom, target: framing.target };
    for (const mate of mates) {
      total++;
      if (!mate.linked) beyondLinks++;
      const at = state.nodes[state.index.get(mate.name)];
      if (!at) continue;
      const p = layout.project(at.pos, cam, WIDTH, HEIGHT);
      if (p.x >= 0 && p.x <= WIDTH && p.y >= 0 && p.y <= HEIGHT) onCanvasCount++;
    }
  }
  if (total === 0) return null;
  return {
    withCompanions,
    median: Number((total / withCompanions).toFixed(1)),
    beyondLinks: beyondLinks / total,
    visible: onCanvasCount / total,
  };
}

const reach = coUseReach();

/**
 * How far the clusters found in the links agree with the curated index.
 *
 * Reported, not gated. A low number is not a defect in either one — it is the
 * finding: the index is organised by topic and the links by what was worked on
 * together, and where they part company is exactly where the picture has
 * something to say that MEMORY.md does not.
 */
function agreement() {
  let matched = 0;
  for (const c of chosen) {
    const counts = new Map();
    for (const m of c.members) {
      const s = curated.get(m) ?? '(none)';
      counts.set(s, (counts.get(s) ?? 0) + 1);
    }
    matched += Math.max(...counts.values());
  }
  return matched / names.length;
}

const stranded = chosen.filter((c) => c.members.length === 1).length;
const topBridges = layout.bridges(names, graph.edges, clusterOf).slice(0, 3);

const report = {
  source: file ?? 'synthetic',
  nodes: graph.nodes.length,
  edges: graph.edges.length,
  sections: sections.length,
  settleSteps: steps,
  seededRadius: Number(seededRadius.toFixed(1)),
  boundingRadius: Number(radius.toFixed(1)),
  canvas: `${WIDTH}x${HEIGHT}`,
  seededZoom: Number(seededZoom.toFixed(4)),
  fitZoom: Number(zoom.toFixed(4)),
  zoomTravel: `${(seededZoom / zoom).toFixed(2)}x over ${steps} steps`,
  nodesOnCanvas: `${onCanvas}/${graph.nodes.length}`,
  labelsDrawn: plan.drawn.length,
  labelsCollided: plan.collided,
  labelsOffCanvas: plan.offCanvas,
  labelsOverBudget: plan.overBudget,
  labelBudget: layout.LABEL_BUDGET,
  intraOverInter: Number(ratio.toFixed(3)),
  hopsMedian: walk.median,
  hopsMax: walk.max,
  busiest: walk.busiest,
  focusFits: `${walk.onScreen}/${walk.litHere}`,
  focusZoomGain: `${walk.zoomGain.toFixed(2)}x`,
  clusterLadder: levels.map((l) => l.length).join(' → '),
  clustersShown: chosen.length,
  stranded,
  indexAgreement: `${(agreement() * 100).toFixed(0)}%`,
  topBridge: topBridges.map((b) => `${b.name}(${b.spans})`).join(' '),
  affinities: affinities.length,
  affinityPull: pull
    ? `${pull.ratio.toFixed(2)}x vs the same graph without them, over ${pull.pairs} pairs`
    : 'none',
  coUseMemories: reach ? reach.withCompanions : 0,
  coUsePerMemory: reach ? reach.median : 0,
  coUseUnlinked: reach ? `${(reach.beyondLinks * 100).toFixed(0)}%` : 'n/a',
  coUseVisible: reach ? `${(reach.visible * 100).toFixed(0)}% land on the focused canvas` : 'n/a',
};

for (const [k, v] of Object.entries(report)) {
  console.log(`${k.padEnd(18)} ${v}`);
}

// The three historical bugs, as thresholds. Failing here is the whole point:
// these were all "the picture looks a bit wrong", which is not something CI can
// notice, and each one shipped.
const problems = [];
if (report.fitZoom === 1) {
  problems.push('fitZoom is exactly 1 — the fit is a no-op again (scale must not derive from distance alone)');
}
if (onCanvas < graph.nodes.length * 0.9) {
  problems.push(`only ${report.nodesOnCanvas} nodes land on the canvas — the graph is clipped`);
}
if (plan.drawn.length > layout.LABEL_BUDGET) {
  problems.push(`${plan.drawn.length} labels drawn, over the budget of ${layout.LABEL_BUDGET}`);
}
if (Number.isFinite(ratio) && ratio > 0.85) {
  problems.push(`sections are not holding together (intra/inter ${report.intraOverInter}, want well under 1)`);
}
if (walk.onScreen < walk.litHere) {
  problems.push(
    `focusing ${walk.busiest} leaves ${walk.litHere - walk.onScreen} of its ${walk.litHere} `
      + 'neighbours off the canvas — with isolate on, those are simply gone',
  );
}
// A grouping that puts nearly everything in one cluster, or gives nearly every
// memory its own, is not a reading of the corpus — it is the algorithm failing
// to find one, and the picture would be a single ball or a uniform scatter.
if (chosen.length > 1) {
  const biggest = chosen[0].members.length / names.length;
  if (biggest > 0.6) {
    problems.push(
      `the largest cluster holds ${(biggest * 100).toFixed(0)}% of the corpus — that is one ball, not a map`,
    );
  }
  if (stranded / names.length > 0.25) {
    problems.push(
      `${stranded} of ${names.length} memories cluster alone — the links are not being read`,
    );
  }
}
// The failure this view has had twice, in two different forces: a term that is
// wired, computes, and moves nothing. It cannot be seen — the picture is
// plausible either way — so it has to be a number.
if (pull && pull.ratio > 0.95) {
  problems.push(
    `affinities move co-used memories to ${pull.ratio.toFixed(2)}x where they sit without them `
      + '— the second force is inert',
  );
}
// The dashed layer earns its ink by showing something the links do not. If
// almost every companion is already a link neighbour, every dash lies on top of
// an edge and the layer is decoration.
if (reach && reach.beyondLinks < 0.2) {
  problems.push(
    `only ${(reach.beyondLinks * 100).toFixed(0)}% of co-use pairs go beyond the links `
      + '— the dashed layer is drawing what the edges already drew',
  );
}
if (pull && pull.ratio < 0.15) {
  problems.push(
    `affinities collapse co-used memories to ${pull.ratio.toFixed(2)}x where they sit without them `
      + '— the second force is overpowering the links it is meant to qualify',
  );
}
if (walk.zoomGain < 1) {
  problems.push(
    `focusing pulls the camera BACK (${report.focusZoomGain}) — a step should close in on where `
      + 'the reader went, not away from it',
  );
}

if (problems.length) {
  console.error('\nFAIL');
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
console.log('\nOK');
